### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ahmad-siavashi** [OpenBookshelf/DiscreteMathematics-Persian#1]
Dear authors,

First of all, I'd like to thank you for your efforts. Then, I'd like to recommend an update to your `README.md` file to contain more information about your work. In the absence of a compiled `PDF`, that would be very useful.

Bests,
A. Siavsahi

**Comment by TheShayegh** [comment]
Thank you. We are working on it.

**Comment by arefafzali** [comment]
You can find the PDF of the book in the Releases part with its tags.
Or click the below link:
https://github.com/OpenBookshelf/DiscreteMathematics-Persian/releases

**Comment by TheShayegh** [comment]
@ahmad-siavashi 
سلام. با توجه به اینکه شما نیز فارسی‌زبان هستید، بنابراین فکر می‌کنم بتوانیم فارسی صحبت کنیم.
توضیحات مختصری به همراه فهرست فعلی مطالب آماده شده و بر روی صفحه مربوطه قرار گرفت.
توضیحاتی بیشتر به همراه راهنمای همکاری و ... نیز اضافه خواهد شد.
با تشکر.
